# Exploration action
#
# dotX Automation s.r.l.
#
# July 31, 2024

# GOAL
# True if it is the first time the action is called
bool first

# True if the exploration routine should be executed continuously
bool persistent true
---
# RESULT
# Operation result
dua_common_interfaces/CommandResultStamped result
---
# FEEDBACK
