# Navigation operation to a target pose.
#
# dotX Automation <info@dotxautomation.com>
#
# February 20, 2025

# GOAL
# Target pose
geometry_msgs/PoseStamped target_pose
---
# RESULT
# Operation result
dua_common_interfaces/CommandResultStamped result
---
# FEEDBACK
# Current pose
geometry_msgs/PoseStamped current_pose
