# Travel to a specific location from current position.
#
# Roberto Masocco <r.masocco@dotxautomation.com>
#
# June 6, 2023

# GOAL
# Target position and orientation
geometry_msgs/PoseStamped target_pose

# Confidence sphere radius (meters, absolute)
float64 reach_radius

# Indicates whether the robot should stop at the target position or not
bool stop_at_target
---
# RESULT
# Operation result
dua_common_interfaces/CommandResultStamped result
---
# FEEDBACK
# Current pose
geometry_msgs/PoseStamped current_pose

# Current distance from target
float64 distance_from_target
