# Coordinated turn operation: changes heading only.
#
# Roberto Masocco <r.masocco@dotxautomation.com>
#
# June 6, 2023

# GOAL
# Header
std_msgs/Header header

# Desired heading
float64 heading
---
# RESULT
# Operation result
dua_common_interfaces/CommandResultStamped result
---
# FEEDBACK
# Current yaw angle [-PI +PI] (radians)
float64 current_yaw

# Current yaw angle [-180 +180] (degrees)
float64 current_yaw_deg
